name: Bug report
description: Template for bug reports
title: '[Bug]: '
labels:
  - bug
assignees:
  - misieur
body:
  - type: textarea
    attributes:
      label: Describe the bug
      placeholder: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    attributes:
      label: To Reproduce
      placeholder: >-
        Steps to reproduce the behavior: 
        1. Go to '...' 
        2. Click on '....' 
        3. Scroll down to '....' 4. See error
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected behavior
      placeholder: A clear and concise description of what you expected to happen.
  - type: textarea
    attributes:
      label: Screenshots
      placeholder: If applicable, add screenshots to help explain your problem.
  - type: input
    attributes:
      label: Paper Version
      description: Paste your `/version` output here
      placeholder: >-
        This server is running Paper version version-build-branch@commit (date) (Implementing API version version-R0.1-SNAPSHOT)
        You are running the latest version
    validations:
      required: true
  - type: textarea
    attributes:
      label: Additional context
      placeholder: Add any other context about the problem here.
